#!/bin/bash

input=af_input
output=af_output
template=a100-af
cloud=gcloud
max_vms=50
name_prefix=$template
file_weight=100


if [ -z "$STY" ]; then
  echo must be run from a \(GNU\) screen
  exit
fi

source $(dirname $(realpath $0))/command_center_lib.sh

get_additional_files() {
  (
  while read l ; do
    echo $l;  jq < $l | grep Path\": | rev | cut -f2 -d\" | rev | sed "s~^~./$input/~g";
  done 2>/dev/null
  )
}

send_work() {
  sssh rm -rf $output $input workdir work_done final_done &>/dev/null
  pv $work_zstd | sssh 'zstd -d | tar -xf -'
#  ls af_output/ |
#   sssh 'while read dir; mkdir -p $dir'
  sssh killall -9 bash
  cat << EOF | sssh cat - \> work.sh
  ln -fs /root/mlibs /root/public_databases
  rm -rf $output workdir
  mkdir $output workdir
  cd $input
  rm /root/work_done /root/final_done
  for i in *json; do
    try=0
    success=1
    while [ \$try -lt 3 ]; do
      if ls /root/workdir/\$i/*/*cif &>/dev/null; then
        success=0
        break
      fi
      try=\$((try+1))
      rm -rf /root/workdir/\$i
      mkdir -p /root/workdir/\$i
      cp /root/$input/\$i /root/workdir/\$i/
      [ -e /root/$output/\$i ] && continue
      docker rm main
      docker run --name main \
        -e PYTHONUNBUFFERED=1 \
        --volume /root/:/root/ \
        --gpus=all \
        alphafold3 \
        python -u run_alphafold.py \
        --run_inference=True \
        --run_data_pipeline=False \
        --json_path=/root/$input/\$i \
        --model_dir=/root/models \
        --output_dir=/root/workdir/\$i
      docker wait main
      docker logs main &>> /root/workdir/\$i/log
      docker rm main
    done

    mv /root/workdir/\$i /root/$output/
    echo \$i >> /root/work_done

  done
  touch /root/final_done
EOF
}

if ! ls $input/ | grep -q json &>/dev/null; then
  echo $input empty
exit 2
fi
mkdir -p $output

get_files() {
  ls $input $output | grep json | sort | uniq -u |
    while read l; do
      [ -e "$input/$l" ] && echo $input/$l
    done
}


created_vms=()

trap cleanup EXIT
trap cleanup ERR

echo refreshing state please wait
wait_for_lock
refresh_state

main_af &
fancy
