#!/bin/bash -x

input=$1
output=boltz_outputs_${input}
template=a100-boltz
cloud=gcloud
max_vms=1
name_prefix=$template
file_weight=1000

if [ -z "$STY" ]; then
  echo must be run from a \(GNU\) screen
  exit
fi

source $(dirname $(realpath $0))/command_center_lib.sh

get_additional_files() {
  (
  while read l ; do
    echo $l; yq -r '.sequences[].protein.msa' < $l | grep -v null
  done
  ) # | tee debug
}

send_work() {
  sssh rm -rf $output $input workdir work_done final_done &>/dev/null
  pv $work_zstd | sssh 'zstd -d | tar -xf -'

  cat << EOF | sssh cat - \> work.sh
  . venv/bin/activate
  pkill python -9
  touch /root/.boltz/mols.tar
  rm -rf $output workdir /root/work_done /root/final_done
  mkdir $output workdir

  for i in $input/*yaml; do
    mkdir -p /root/workdir/\$i
    [ -e /root/$output/\$i ] && continue

    if boltz predict \$i --out_dir /root/workdir/\$(basename \$i) --use_potentials; then
      mv /root/workdir/\$(basename \$i)/* /root/$output/\$(basename \$i)
      echo \$(basename \$i) >> work_done
    fi

  done
  touch /root/final_done
EOF
}

if ! ls $input/*yaml &>/dev/null; then
  echo $input empty
  exit 2
fi

mkdir -p $output
get_files() {
  ls $input $output | grep -v a3m | grep yaml | sort | uniq -u |
    while read l; do
      [ -e $input/$l ] && echo $input/$l
    done
}

files=( $(get_files) )
files_m=$(( ${#files[@]} -1 ))
step=$(( files_m / max_vms ))
files_i=0

created_vms=()

trap cleanup EXIT
trap cleanup ERR

echo refreshing state please wait
wait_for_lock
refresh_state

main_af &
set +x
fancy

wait
