#!/bin/bash
export DIRPATH="$(dirname $(realpath $0))"
export tfvar=terraform.tfvars.json
export tfvar_tmp=$DIRPATH/tmp_$tfvar
export tfvar=$DIRPATH/$tfvar
source $(dirname $(realpath $0))/lib.sh
name=$( cut -d @ -f2 <<< $1)
delete_vm
