#!/bin/bash
source $(dirname $(realpath $0))/lib.sh

name=$1

if [ -z "$name" ];then
  for name in $(eval echo $(list_running)); do
    echo -n $name :\ \ \ 
    check_health; code=$?
    case $code in
      1) echo powering up; power_vm;;
      2) echo reseting; reset_vm;;
      0) echo ok;;
    esac
  done
else
  check_health; code=$?
  case $code in
    1) echo powering up; power_vm;;
    2) echo reseting; reset_vm;;
    0) echo ok;;
  esac
  get_ip_from_name
fi

wait
